AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  #VPC:
  #  Type: "AWS::EC2::VPC::Id"

  #Subnets:
  #  Type: "List<AWS::EC2::Subnet::Id>"

  ServiceName:
    Type: String
    AllowedPattern: "[a-z0-9]+"

  ECRRepositoryName:
    Type: String

  DockerImageTag:
    Type: String
    Default: latest

  DesiredCount:
    Type: Number    
    Default: 0

Resources:
  ECSExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      MaxSessionDuration: 3600
      Path: /service-role/
      Policies:
        - PolicyName: "GetSecrets"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource:
                  - !Ref DatabaseConnectionStringSecret

  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      MaxSessionDuration: 3600
      Path: /service-role/
      Policies:
        - PolicyName: "SQS" 
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                Resource:
                  - !GetAtt Queue.Arn

  Queue:
    Type: "AWS::SQS::Queue"
    Properties:
      ReceiveMessageWaitTimeSeconds: 20

  FargateCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ServiceName

  FargateService: #FIXME ensure no public IPs (i.e. place fargate tasks in private subnets)
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref FargateCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: application
          ContainerPort: 80
          TargetGroupArn: !ImportValue TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Ref: FargateSecurityGroup
          #Subnets: !Ref Subnets
          Subnets: !Split [",", !ImportValue PrivateSubnets]
      PlatformVersion: LATEST
      SchedulingStrategy: REPLICA
      TaskDefinition: !Ref TaskDefinition

  FargateSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: HTTP 80
      SecurityGroupIngress:
        - FromPort: 80
          IpProtocol: tcp
          #SourceSecurityGroupId: !GetAtt LoadBalancerSecurityGroup.GroupId #NLBs cannot have security groups
          CidrIp: "0.0.0.0/0"
          ToPort: 80          
      #VpcId: !Ref VPC
      VpcId: !ImportValue VPC

  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Cpu: "1024"
          Essential: true
          Image: !Join
            - ""
            - - Ref: "AWS::AccountId"
              - .dkr.ecr.
              - Ref: "AWS::Region"
              - .amazonaws.com/
              - !Ref ECRRepositoryName
              - ":"
              - !Ref DockerImageTag
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TaskLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          Memory: "2048"
          MemoryReservation: "2048"
          Name: application
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          Secrets:
            - Name: ASPNETCORE_ConnectionStrings__main
              ValueFrom: !Ref DatabaseConnectionStringSecret
          Environment:
            - Name: ASPNETCORE_queues__main
              Value: !Ref Queue
      Cpu: "1024"
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      Family: !Ref ServiceName
      Memory: "2048"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

  TaskLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /ecs/
          - !Ref ServiceName
      RetentionInDays: 7

  ErrorCountMetricFilter: 
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: !Ref TaskLogGroup
      FilterPattern: '{ $.Level = "Error"  || $.Level = "Fatal" }'
      MetricTransformations: 
        - MetricValue: "1"
          MetricNamespace: !Ref ServiceName
          MetricName: "ErrorCount"
          DefaultValue: 0

  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmDescription: 'Errors in log'
      AlarmActions:
        - !Ref AlarmTopic
      Namespace: !Ref ServiceName
      MetricName: "ErrorCount"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      TreatMissingData: notBreaching

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Sub "${ServiceName} Error"

  DatabaseSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: 'Secret for RDS instance'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  DatabaseConnectionStringSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      SecretString: !Join ['', ['Server=', !GetAtt Database.Endpoint.Address, ';Database=tempdb;User Id=', '{{resolve:secretsmanager:', !Ref DatabaseSecret, ':SecretString:username}}', ";Password='", '{{resolve:secretsmanager:', !Ref DatabaseSecret, ':SecretString:password}}', "'" ]]
    
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.small
      Engine: sqlserver-web
      EngineVersion: 14.00.3223.3.v1
      LicenseModel: license-included
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DatabaseSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DatabaseSecret, ':SecretString:password}}' ]]
      BackupRetentionPeriod: 0
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
        - !Ref DatabaseSG

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: db subnet group
      #SubnetIds: !Ref Subnets
      SubnetIds: !Split [",", !ImportValue PrivateSubnets]

  DatabaseSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SQLServer
      SecurityGroupIngress:
        - FromPort: 1433
          IpProtocol: tcp
          SourceSecurityGroupId: !GetAtt FargateSecurityGroup.GroupId
          ToPort: 1433
      #VpcId: !Ref VPC
      VpcId: !ImportValue VPC

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DatabaseSecret
      TargetId: !Ref Database
      TargetType: AWS::RDS::DBInstance

Outputs:
  AlarmTopicArn:
    Value: !Ref AlarmTopic

  Queue:
    Value: !Ref Queue

  LogGroup:
    Value: !Ref TaskLogGroup
