AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Trail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt TrailLogs.Arn
      CloudWatchLogsRoleArn: !GetAtt TrailLogsRole.Arn
      IsLogging: True
      S3BucketName: !Ref TrailBucket
    DependsOn:
      - TrailBucketPolicy

  TrailBucket:
    Type: "AWS::S3::Bucket"

  TrailBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument: !Sub |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "AWSCloudTrailAclCheck20150319",
                    "Effect": "Allow",
                    "Principal": {"Service": "cloudtrail.amazonaws.com"},
                    "Action": "s3:GetBucketAcl",
                    "Resource": "arn:aws:s3:::${TrailBucket}"
                },
                {
                    "Sid": "AWSCloudTrailWrite20150319",
                    "Effect": "Allow",
                    "Principal": {"Service": "cloudtrail.amazonaws.com"},
                    "Action": "s3:PutObject",
                    "Resource": "arn:aws:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*",
                    "Condition": {"StringEquals": {"s3:x-amz-acl": "bucket-owner-full-control"}}
                }
            ]
        }

  TrailLogs:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /cloudtrail/
          - !Ref AWS::StackName
      RetentionInDays: 7

  TrailLogsRole: 
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - "sts:AssumeRole"
      MaxSessionDuration: 3600
      Policies:
        - PolicyName: "CloudWatchLogs" 
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - !GetAtt TrailLogs.Arn

Outputs:
  TrailLogs:
    Value: !Ref TrailLogs

  TrailBucket:
    Value: !Ref TrailBucket
