AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ECRRepositoryName:
    Type: String
    AllowedPattern: "[a-z0-9]+"

Resources:
  ECRRepository:
    Type: "AWS::ECR::Repository"
    DeletionPolicy: Delete
    Properties:
      RepositoryName: !Ref ECRRepositoryName
      LifecyclePolicy: 
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images older than 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  ECRRepositoryName:
    Value: !Ref ECRRepository
